"""initial schema

Revision ID: 1fb0ea896219
Revises: 
Create Date: 2026-09-03 22:17:29.815002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb0ea896219'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id', name=op.f('pk_admins'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('bot_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('backup_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('backup_directory', sa.Text(), server_default=sa.text("'./backups'"), nullable=False),
    sa.Column('compression_format', sa.Enum('zip', name='compressionformat', native_enum=False), server_default=sa.text("'zip'"), nullable=False),
    sa.Column('compression_level', sa.Integer(), server_default=sa.text('6'), nullable=False),
    sa.Column('retention_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('retention_keep_last', sa.Integer(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('proxy_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('proxy_url', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('compression_level >= 0 AND compression_level <= 9', name=op.f('ck_app_settings_compression_level_range')),
    sa.CheckConstraint('id = 1', name=op.f('ck_app_settings_singleton_id')),
    sa.CheckConstraint('retention_keep_last >= 1', name=op.f('ck_app_settings_retention_keep_last_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200, collation='NOCASE'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('database_type', sa.Enum('sqlite', name='databasetype', native_enum=False), server_default=sa.text("'sqlite'"), nullable=False),
    sa.Column('database_path', sa.Text(), nullable=False),
    sa.Column('media_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('media_path', sa.Text(), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('schedule_interval', sa.Integer(), server_default=sa.text('6'), nullable=False),
    sa.Column('schedule_unit', sa.Enum('minutes', 'hours', 'days', name='scheduleunit', native_enum=False), server_default=sa.text("'hours'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('schedule_interval >= 1', name=op.f('ck_projects_schedule_interval_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    op.create_table('backup_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='backupstatus', native_enum=False), nullable=False),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('database_size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_size_bytes', sa.Integer(), nullable=False),
    sa.Column('archive_size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_file_count', sa.Integer(), nullable=False),
    sa.Column('checksum_algorithm', sa.String(length=50), nullable=True),
    sa.Column('checksum_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('archive_size_bytes >= 0', name=op.f('ck_backup_history_archive_size_non_negative')),
    sa.CheckConstraint('database_size_bytes >= 0', name=op.f('ck_backup_history_database_size_non_negative')),
    sa.CheckConstraint('media_file_count >= 0', name=op.f('ck_backup_history_media_file_count_non_negative')),
    sa.CheckConstraint('media_size_bytes >= 0', name=op.f('ck_backup_history_media_size_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_backup_history_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_history'))
    )
    with op.batch_alter_table('backup_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_history_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_history_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_history_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_history_status'))
        batch_op.drop_index(batch_op.f('ix_backup_history_started_at'))
        batch_op.drop_index(batch_op.f('ix_backup_history_project_id'))

    op.drop_table('backup_history')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    op.drop_table('app_settings')
    op.drop_table('admins')
    # ### end Alembic commands ###
